project_id = "rryvwkqupkhpdlevopkk"


[functions.tmdb-proxy]
verify_jwt = false

[functions.activate-scheduled]
verify_jwt = false

[functions.send-push-notifications]
verify_jwt = false

[functions.fetch-games]
verify_jwt = false

[functions.update-live-games]
verify_jwt = false
